[package]
name = "diffs"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
argh = "0.1.4"
colored = "2.0.0"
git_commands = { path = "git_commands", version = "0.2.0" }
regex = "1.5.4"
once_cell = "1.8.0"
url = "2.2.2"
